# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='next_episode_run_time',
            field=models.DateField(null=True),
        ),
    ]
