# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='id_tv_show_tmdb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='in_production',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='nb_season',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
