# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0002_auto_20171010_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='id_tv_show_tmdb',
            new_name='tmdb_id',
        ),
    ]
