# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0003_auto_20171017_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='num',
        ),
        migrations.AddField(
            model_name='season',
            name='broadcast_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='nb_episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='overview',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='season_nb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='tmdb_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='tv_show',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_series.TvShow'),
        ),
    ]
