# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_series', '0004_auto_20171018_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishes', models.ManyToManyField(to='app_series.TvShow')),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='num',
        ),
        migrations.RemoveField(
            model_name='season',
            name='broadcast_date',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_nb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='overview',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='tmdb_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='tv_season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_series.Season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='vote_average',
            field=models.IntegerField(default=0),
        ),
    ]
