# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_nb', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, null=True)),
                ('overview', models.CharField(max_length=1000, null=True)),
                ('vote_average', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_nb', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, null=True)),
                ('overview', models.CharField(max_length=1000, null=True)),
                ('nb_of_episodes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(null=True)),
                ('nb_of_seasons', models.IntegerField(default=0)),
                ('is_in_production', models.BooleanField(default=True)),
                ('next_episode_run_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishes', models.ManyToManyField(to='app_gitmyseries.TvShow')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='tv_show',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_gitmyseries.TvShow'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_gitmyseries.Season'),
        ),
    ]
