# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gitmyseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='url_image',
            field=models.TextField(null=True),
        ),
    ]
